server:
  port: 7099
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/myessen
    username: postgres
    password: pepeeselmejor
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
  issuer: myessen
logging:
  level:
    org:
      springframework:
        security: TRACE
